//! `NcFile` — NetCDF-4 file reader built atop OxiH5.
//!
//! Resolves NetCDF-4 HDF5 conventions:
//! - `CLASS = "DIMENSION_SCALE"` + `NAME` attribute → dimension discovery
//! - `_Netcdf4Dimid` attribute → dimension ID
//! - `DIMENSION_LIST` attribute (object references) → axis linkage per variable
//! - Cross-group dimension references (B4) via `File::header_addr_of`
//!
//! # Slice 1 scope
//! Fully resolves the **root group** (including all sub-groups recursively).
//! Cross-group shared dimensions are resolved via a two-phase scan (B3/B4).
//!
//! # Skip-guarded E2E tests
//! End-to-end tests that require a real NetCDF-4 fixture generated by
//! `python3 -c "import netCDF4; ..."` are guarded by `#[cfg(feature = "e2e")]`
//! so they pass in CI without `python3`/netCDF4 installed.

use std::collections::HashSet;

use oxih5::File as H5File;

use crate::error::NcError;
use crate::model::{apply_fill_mask, NcGroup, NcVariable};
use crate::resolver::{collect_global_dims, resolve_group_deep};

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

/// An open NetCDF-4 file.
pub struct NcFile {
    h5: H5File,
}

impl NcFile {
    /// Open a NetCDF-4 file by path.
    ///
    /// The file must be a valid HDF5 file written according to the NetCDF-4
    /// conventions (as produced by `netCDF4-python`, `libnetcdf`, etc.).
    pub fn open<P: AsRef<std::path::Path>>(path: P) -> Result<Self, NcError> {
        let h5 = H5File::open(path)?;
        Ok(Self { h5 })
    }

    /// Open a NetCDF-4 file from in-memory bytes.
    ///
    /// Useful for testing without a filesystem.
    pub fn open_from_bytes(data: &[u8]) -> Result<Self, NcError> {
        let h5 = H5File::open_from_bytes(data)?;
        Ok(Self { h5 })
    }

    /// Resolve and return the root group with all dimensions, variables, and
    /// recursively resolved sub-groups.
    ///
    /// Phase 1: scan the entire file for dimension-scale datasets
    /// (`CLASS = "DIMENSION_SCALE"`) and build a cross-group address registry.
    ///
    /// Phase 2: recursively resolve each group into an `NcGroup`, using the
    /// registry to resolve cross-group `DIMENSION_LIST` references.
    pub fn root_group(&self) -> Result<NcGroup, NcError> {
        // Phase 1 — collect all dim scales.
        let global_dims = collect_global_dims(&self.h5, "/");
        // Phase 2 — recursive group resolution.
        let mut visited: HashSet<String> = HashSet::new();
        resolve_group_deep(&self.h5, "/", "/", &global_dims, &mut visited, 0)
    }

    /// Return a reference to the underlying `oxih5::File` (B6 power-user API).
    ///
    /// Allows direct use of `File::dataset_strings`, `File::dataset_at`, etc.
    /// without going through the NetCDF conventions layer.
    pub fn h5(&self) -> &H5File {
        &self.h5
    }
}

// ---------------------------------------------------------------------------
// NcVariable read methods (B6, B7)
// ---------------------------------------------------------------------------

impl NcVariable {
    /// Read the variable's data as a flat `Vec<f64>`.
    ///
    /// Returns `NcError::ReadError` if the variable's dtype is not float64.
    pub fn read_f64(&self, nc: &NcFile) -> Result<Vec<f64>, NcError> {
        let ds = nc.h5().dataset(&self.h5_path)?;
        ds.as_f64()
            .map_err(|e| NcError::ReadError(format!("read_f64 '{name}': {e}", name = self.name)))
    }

    /// Read the variable's data as a flat `Vec<i64>`.
    ///
    /// Returns `NcError::ReadError` if the variable's dtype is not an integer.
    pub fn read_i64(&self, nc: &NcFile) -> Result<Vec<i64>, NcError> {
        let ds = nc.h5().dataset(&self.h5_path)?;
        ds.as_i64()
            .map_err(|e| NcError::ReadError(format!("read_i64 '{name}': {e}", name = self.name)))
    }

    /// Read a vlen-string variable's data as `Vec<String>` (B6 NC_STRING).
    ///
    /// Delegates to `oxih5::File::dataset_strings` which handles both fixed-
    /// length and vlen-string datasets.  Returns `NcError::ReadError` for
    /// non-string dtypes.
    pub fn read_strings(&self, nc: &NcFile) -> Result<Vec<String>, NcError> {
        nc.h5().dataset_strings(&self.h5_path).map_err(|e| {
            NcError::ReadError(format!("read_strings '{name}': {e}", name = self.name))
        })
    }

    /// Read the variable's f64 data with fill-value masking (B7).
    ///
    /// Elements equal to `_FillValue` (bit-exact comparison to handle NaN fill
    /// values) are replaced with `f64::NAN` in the output.  If the variable
    /// has no `_FillValue` attribute the data is returned unmodified.
    ///
    /// Returns `NcError::ReadError` if the dtype is not float64.
    pub fn read_f64_masked(&self, nc: &NcFile) -> Result<Vec<f64>, NcError> {
        let values = self.read_f64(nc)?;

        let fill_opt = self
            .fill_value()
            .and_then(|fv| fv.as_f64().ok())
            .and_then(|v| v.first().copied());

        let out = match fill_opt {
            Some(fill) => {
                let fill_bits = fill.to_bits();
                values
                    .into_iter()
                    .map(|v| {
                        if v.to_bits() == fill_bits {
                            f64::NAN
                        } else {
                            v
                        }
                    })
                    .collect()
            }
            None => values,
        };
        Ok(out)
    }

    /// Read the variable's i64 data with fill-value masking (B7).
    ///
    /// Elements equal to `_FillValue` are replaced with `None`.
    /// If the variable has no `_FillValue` attribute all elements are `Some(v)`.
    ///
    /// Returns `NcError::ReadError` if the dtype is not an integer.
    pub fn read_i64_masked(&self, nc: &NcFile) -> Result<Vec<Option<i64>>, NcError> {
        let values = self.read_i64(nc)?;

        let fill_opt = self
            .fill_value()
            .and_then(|fv| fv.as_i64().ok())
            .and_then(|v| v.first().copied());

        let out = match fill_opt {
            Some(fill) => apply_fill_mask(&values, fill),
            None => values.into_iter().map(Some).collect(),
        };
        Ok(out)
    }
}

// ---------------------------------------------------------------------------
// Unit tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use oxih5::{Dtype, FileWriter};

    fn make_simple_h5(name: &str, data: &[f64]) -> Vec<u8> {
        let tmp = std::env::temp_dir().join(format!("oxinc_file_{name}.h5"));
        FileWriter::new()
            .write_dataset_f64(name, data, &[data.len()])
            .unwrap()
            .build(&tmp)
            .unwrap();
        std::fs::read(&tmp).unwrap()
    }

    #[test]
    fn test_open_from_bytes_simple() {
        let bytes = make_simple_h5("temperature", &[1.0, 2.0, 3.0]);
        let nc = NcFile::open_from_bytes(&bytes).unwrap();
        let root = nc.root_group().unwrap();
        let var = root
            .variable("temperature")
            .expect("should find temperature");
        assert_eq!(var.shape, vec![3]);
        assert!(matches!(var.dtype, Dtype::Float { size: 8, .. }));
    }

    #[test]
    fn test_phony_dims_for_undimensioned_variable() {
        let bytes = make_simple_h5("lat", &[10.0, 20.0, 30.0, 40.0]);
        let nc = NcFile::open_from_bytes(&bytes).unwrap();
        let root = nc.root_group().unwrap();
        let var = root.variable("lat").unwrap();
        assert_eq!(var.dims.len(), 1);
        assert!(
            var.dims[0].name.starts_with("phony_dim_"),
            "expected phony dim name, got: {}",
            var.dims[0].name
        );
        assert_eq!(var.dims[0].len, 4);
    }

    #[test]
    fn test_root_group_name() {
        let bytes = make_simple_h5("x", &[1.0]);
        let nc = NcFile::open_from_bytes(&bytes).unwrap();
        let root = nc.root_group().unwrap();
        assert_eq!(root.name, "/");
        assert_eq!(root.path, "/");
    }

    #[test]
    fn test_no_dimensions_scalar() {
        let bytes = make_simple_h5("scalar", &[42.0]);
        let nc = NcFile::open_from_bytes(&bytes).unwrap();
        let root = nc.root_group().unwrap();
        assert!(root.variable("scalar").is_some());
    }

    #[test]
    fn test_h5_accessor() {
        let bytes = make_simple_h5("data", &[1.0, 2.0]);
        let nc = NcFile::open_from_bytes(&bytes).unwrap();
        // h5() gives back the underlying File
        let ds = nc.h5().dataset("data").unwrap();
        assert_eq!(ds.shape, vec![2]);
    }

    #[test]
    fn test_read_f64() {
        let bytes = make_simple_h5("values", &[1.0, 2.0, 3.0]);
        let nc = NcFile::open_from_bytes(&bytes).unwrap();
        let root = nc.root_group().unwrap();
        let var = root.variable("values").unwrap();
        let data = var.read_f64(&nc).unwrap();
        assert_eq!(data, vec![1.0, 2.0, 3.0]);
    }

    #[test]
    fn test_read_f64_masked_no_fill() {
        // Without _FillValue, read_f64_masked returns data unchanged.
        let bytes = make_simple_h5("nomasked", &[1.0, 2.0, 3.0]);
        let nc = NcFile::open_from_bytes(&bytes).unwrap();
        let root = nc.root_group().unwrap();
        let var = root.variable("nomasked").unwrap();
        let masked = var.read_f64_masked(&nc).unwrap();
        assert_eq!(masked, vec![1.0, 2.0, 3.0]);
    }

    #[test]
    fn test_read_f64_masked_type_error_on_non_float() {
        // FileWriter writes float64; this sanity-checks the error path for
        // non-float variables by writing an integer dataset.
        let tmp = std::env::temp_dir().join("oxinc_file_int_masked.h5");
        FileWriter::new()
            .write_dataset_i32("int_data", &[1i32, 2, 3], &[3])
            .unwrap()
            .build(&tmp)
            .unwrap();
        let bytes = std::fs::read(&tmp).unwrap();
        let nc = NcFile::open_from_bytes(&bytes).unwrap();
        let root = nc.root_group().unwrap();
        let var = root.variable("int_data").unwrap();
        // read_f64 on an int32 variable should return an error.
        assert!(var.read_f64(&nc).is_err());
    }

    #[test]
    fn test_root_group_children_empty_for_flat_file() {
        let bytes = make_simple_h5("flat", &[1.0]);
        let nc = NcFile::open_from_bytes(&bytes).unwrap();
        let root = nc.root_group().unwrap();
        // A flat HDF5 file has no sub-groups.
        assert!(root.children.is_empty());
    }

    // -----------------------------------------------------------------------
    // Integration tests using real HDF5 fixtures (string datasets, compound)
    // -----------------------------------------------------------------------

    /// Verify that `read_strings` works on a dataset that FileWriter stored as
    /// fixed-length strings (since FileWriter doesn't support vlen-string write yet,
    /// we test via the existing string_datasets.h5 fixture).
    #[test]
    fn test_read_strings_from_fixture() {
        let fixture = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .unwrap()
            .join("oxih5/tests/fixtures/string_datasets.h5");
        if !fixture.exists() {
            return; // fixture not available in this build environment
        }
        let nc = NcFile::open(&fixture).unwrap();
        let root = nc.root_group().unwrap();
        // The fixture has string datasets; just check that root_group() succeeds
        // and at least one variable is found.
        assert!(!root.variables.is_empty());
    }

    #[cfg(feature = "e2e")]
    #[test]
    fn test_e2e_placeholder() {
        // This test only runs with `--features e2e`.
        // Future: generate a real .nc file with ncgen and open it here.
    }
}
