//! `NcFile` — NetCDF-4 file reader built atop OxiH5.
//!
//! Resolves NetCDF-4 HDF5 conventions:
//! - `CLASS = "DIMENSION_SCALE"` + `NAME` attribute → dimension discovery
//! - `_Netcdf4Dimid` attribute → dimension ID
//! - `DIMENSION_LIST` attribute (object references) → axis linkage per variable
//! - `REFERENCE_LIST` (informational, not required for Slice 1)
//!
//! # Slice 1 scope
//! Fully resolves the **root group only**.  Sub-groups are discovered by name
//! but not recursively resolved into `NcGroup` objects (see `subgroup_names`).
//! Cross-group shared dimensions are not supported in Slice 1.
//!
//! # Skip-guarded E2E tests
//! End-to-end tests that require a real NetCDF-4 fixture generated by
//! `python3 -c "import netCDF4; ..."` are guarded by `#[cfg_attr(not(feature =
//! "e2e"), ignore)]` so they pass in CI without `python3`/netCDF4 installed.

use std::collections::HashMap;

use oxih5::File as H5File;

use crate::conventions::{is_reserved_attr, parse_pure_dim_sentinel, phony_dim_name};
use crate::error::NcError;
use crate::model::{NcAttribute, NcAxis, NcDimension, NcGroup, NcVariable};

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

/// An open NetCDF-4 file.
pub struct NcFile {
    h5: H5File,
}

impl NcFile {
    /// Open a NetCDF-4 file by path.
    ///
    /// The file must be a valid HDF5 file written according to the NetCDF-4
    /// conventions (as produced by `netCDF4-python`, `libnetcdf`, etc.).
    pub fn open<P: AsRef<std::path::Path>>(path: P) -> Result<Self, NcError> {
        let h5 = H5File::open(path)?;
        Ok(Self { h5 })
    }

    /// Open a NetCDF-4 file from in-memory bytes.
    ///
    /// Useful for testing without a filesystem.
    pub fn open_from_bytes(data: &[u8]) -> Result<Self, NcError> {
        let h5 = H5File::open_from_bytes(data)?;
        Ok(Self { h5 })
    }

    /// Resolve and return the root group with all dimensions and variables.
    ///
    /// This performs a full Slice 1 pass:
    /// 1. Walk datasets in the root group.
    /// 2. Identify dimension scales (CLASS = DIMENSION_SCALE + _Netcdf4Dimid).
    /// 3. For each variable, resolve DIMENSION_LIST object references to dimension IDs.
    /// 4. Validate axis lengths match dimension lengths.
    pub fn root_group(&self) -> Result<NcGroup, NcError> {
        resolve_group(&self.h5, "/")
    }
}

// ---------------------------------------------------------------------------
// Internal resolver
// ---------------------------------------------------------------------------

/// Resolve a single HDF5 group at `group_path` into an `NcGroup`.
fn resolve_group(h5: &H5File, group_path: &str) -> Result<NcGroup, NcError> {
    let grp = h5.group(group_path)?;

    // -----------------------------------------------------------------------
    // 1. Collect group-level attributes.
    // -----------------------------------------------------------------------
    let group_attr_views = grp.attr_views()?;
    let group_attrs: Vec<NcAttribute> = group_attr_views
        .iter()
        .filter(|v| !is_reserved_attr(v.name()))
        .map(|v| NcAttribute::new(v.attr.clone()))
        .collect();

    // -----------------------------------------------------------------------
    // 2. Enumerate all dataset names in this group.
    // -----------------------------------------------------------------------
    let ds_names = grp.datasets()?;
    let subgroup_names = grp.groups()?;

    // -----------------------------------------------------------------------
    // 3. Find dimension scales: datasets with CLASS = "DIMENSION_SCALE".
    //    Record: name → NcDimension (with id from _Netcdf4Dimid, or auto-assigned).
    // -----------------------------------------------------------------------
    // dim_id_map: Netcdf4Dimid → NcDimension
    let mut dim_by_id: HashMap<u32, NcDimension> = HashMap::new();
    // ds_name → dim_id, for variables that are coord vars
    let mut coord_var_dimid: HashMap<String, u32> = HashMap::new();

    // We also collect the object-header addresses of dimension-scale datasets
    // so we can look them up when resolving DIMENSION_LIST references.
    // dim_addr_map: object-header address → dim_id
    let mut dim_addr_to_dimid: HashMap<u64, u32> = HashMap::new();

    let mut phony_counter: u32 = 0;

    for ds_name in &ds_names {
        let full_path = dataset_path(group_path, ds_name);
        let attr_views = match h5.attr_views(&full_path) {
            Ok(v) => v,
            Err(_) => continue,
        };

        // Check CLASS attribute
        let class_attr = attr_views.iter().find(|v| v.name() == "CLASS");
        let is_dim_scale = class_attr
            .and_then(|v| v.as_str_fixed())
            .map(|s| s.trim() == "DIMENSION_SCALE")
            .unwrap_or(false);

        if !is_dim_scale {
            continue;
        }

        // Retrieve _Netcdf4Dimid
        let dim_id_opt: Option<u32> = attr_views
            .iter()
            .find(|v| v.name() == "_Netcdf4Dimid")
            .and_then(|v| v.as_i64())
            .and_then(|i| u32::try_from(i).ok());

        // Retrieve NAME to detect pure-dim sentinels and dimension length.
        let name_attr = attr_views.iter().find(|v| v.name() == "NAME");
        let nc_name_str = name_attr.and_then(|v| v.as_str_fixed());

        // Dataset shape to determine length.
        let ds = match h5.dataset(&full_path) {
            Ok(d) => d,
            Err(_) => continue,
        };
        let dim_len = ds.shape.first().copied().unwrap_or(0) as u64;

        // Detect pure-dim sentinel (not a coordinate variable).
        let (is_unlimited, resolved_name) = if let Some(ref s) = nc_name_str {
            let sentinel_len = parse_pure_dim_sentinel(s);
            if sentinel_len.is_some() {
                // Pure dimension — not a variable.
                (false, ds_name.clone())
            } else {
                (false, ds_name.clone())
            }
        } else {
            (false, ds_name.clone())
        };

        let dim_id = if let Some(id) = dim_id_opt {
            id
        } else {
            // No _Netcdf4Dimid — assign a phony ID.
            let id = phony_counter;
            phony_counter += 1;
            id
        };

        if dim_by_id.contains_key(&dim_id) {
            return Err(NcError::DuplicateDimId(dim_id));
        }

        let dim = NcDimension {
            name: resolved_name.clone(),
            len: dim_len,
            id: dim_id,
            is_unlimited,
        };
        dim_by_id.insert(dim_id, dim);
        coord_var_dimid.insert(ds_name.clone(), dim_id);

        // Record the HDF5 object address for DIMENSION_LIST resolution.
        // We use the attr_views path trick: re-open the dataset to get its attrs
        // which give us the header address indirectly.  Instead, we use the
        // walk-based address resolution below.
    }

    // -----------------------------------------------------------------------
    // 4. Prepare addr→dim_id map (filled lazily during variable processing below).
    //
    // DIMENSION_LIST attribute holds object-reference addresses pointing to
    // dimension-scale datasets.  We resolve them lazily via `lookup_dimid_from_addr`
    // as each variable is processed, caching results in `dim_addr_to_dimid`.
    // -----------------------------------------------------------------------

    // -----------------------------------------------------------------------
    // 5. Process variables (all non-coord-var datasets + coord vars).
    // -----------------------------------------------------------------------
    let mut variables: Vec<NcVariable> = Vec::new();
    let mut phony_dim_fallback: u32 = phony_counter;

    for ds_name in &ds_names {
        let full_path = dataset_path(group_path, ds_name);
        let ds = match h5.dataset(&full_path) {
            Ok(d) => d,
            Err(_) => continue,
        };
        let attr_views = match h5.attr_views(&full_path) {
            Ok(v) => v,
            Err(_) => continue,
        };

        let is_coord = coord_var_dimid.contains_key(ds_name.as_str());

        // Collect user-facing attributes (skip reserved names).
        let nc_attrs: Vec<NcAttribute> = attr_views
            .iter()
            .filter(|v| !is_reserved_attr(v.name()))
            .map(|v| NcAttribute::new(v.attr.clone()))
            .collect();

        // Determine shape as Vec<u64>
        let shape: Vec<u64> = ds.shape.iter().map(|&s| s as u64).collect();
        let rank = shape.len();

        // Resolve DIMENSION_LIST attribute → axis linkage.
        let dim_list_view = attr_views.iter().find(|v| v.name() == "DIMENSION_LIST");

        let dims: Vec<NcAxis> = if let Some(dl_view) = dim_list_view {
            match dl_view.as_object_refs() {
                Ok(refs) => {
                    if refs.len() != rank {
                        return Err(NcError::DimensionListArity {
                            var: ds_name.clone(),
                            found: refs.len(),
                            rank,
                        });
                    }
                    let mut axes = Vec::with_capacity(rank);
                    for (axis_idx, &obj_addr) in refs.iter().enumerate() {
                        let var_len = shape[axis_idx];
                        // Look up dim by address
                        let dim_id_opt = if obj_addr == u64::MAX {
                            None
                        } else {
                            dim_addr_to_dimid.get(&obj_addr).copied().or_else(|| {
                                // Try to resolve by fetching the dim-scale's _Netcdf4Dimid
                                // via object_at.
                                lookup_dimid_from_addr(h5, obj_addr, &dim_by_id).ok()
                            })
                        };

                        let (dim_id, dim_name, dim_len) = match dim_id_opt {
                            Some(id) => {
                                if let Some(dim) = dim_by_id.get(&id) {
                                    if var_len != 0 && dim.len != var_len {
                                        return Err(NcError::AxisLengthMismatch {
                                            var: ds_name.clone(),
                                            axis: axis_idx,
                                            var_len,
                                            dim_len: dim.len,
                                        });
                                    }
                                    (id, dim.name.clone(), dim.len)
                                } else {
                                    return Err(NcError::UnknownDimId {
                                        var: ds_name.clone(),
                                        axis: axis_idx,
                                        dim_id: id,
                                    });
                                }
                            }
                            None => {
                                // Unresolved dim ref: create a phony dimension
                                let phony_id = phony_dim_fallback;
                                phony_dim_fallback += 1;
                                let phony_name = phony_dim_name(phony_id);
                                let phony = NcDimension {
                                    name: phony_name.clone(),
                                    len: var_len,
                                    id: phony_id,
                                    is_unlimited: false,
                                };
                                dim_by_id.insert(phony_id, phony);
                                (phony_id, phony_name, var_len)
                            }
                        };

                        axes.push(NcAxis {
                            dim_id,
                            name: dim_name,
                            len: dim_len,
                        });

                        // Update addr map for future refs
                        if obj_addr != u64::MAX {
                            dim_addr_to_dimid.entry(obj_addr).or_insert(dim_id);
                        }
                    }
                    axes
                }
                Err(_) => {
                    // DIMENSION_LIST may be stored as vlen of refs — handle as best-effort
                    create_phony_axes(&shape, &mut phony_dim_fallback, &mut dim_by_id)
                }
            }
        } else if rank == 0 {
            // Scalar dataset — no axes.
            vec![]
        } else {
            // No DIMENSION_LIST: create phony dimensions for each axis.
            create_phony_axes(&shape, &mut phony_dim_fallback, &mut dim_by_id)
        };

        variables.push(NcVariable {
            name: ds_name.clone(),
            dtype: ds.dtype.clone(),
            dims,
            shape,
            attrs: nc_attrs,
            is_coordinate: is_coord,
            h5_path: full_path,
        });
    }

    // -----------------------------------------------------------------------
    // 6. Collect final dimension list (sorted by id for stable output).
    // -----------------------------------------------------------------------
    let mut dimensions: Vec<NcDimension> = dim_by_id.into_values().collect();
    dimensions.sort_by_key(|d| d.id);

    Ok(NcGroup {
        name: group_path.to_string(),
        path: group_path.to_string(),
        dimensions,
        variables,
        attrs: group_attrs,
        subgroup_names,
    })
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Build a full HDF5 path for a dataset in `group_path`.
fn dataset_path(group_path: &str, ds_name: &str) -> String {
    if group_path == "/" {
        format!("/{ds_name}")
    } else {
        format!("{group_path}/{ds_name}")
    }
}

/// Try to resolve a dimension id from a target object's _Netcdf4Dimid attribute.
///
/// `addr` is the HDF5 object-header address of a dimension-scale dataset.
/// Returns the `u32` dim id if the attribute exists and is readable.
fn lookup_dimid_from_addr(
    h5: &H5File,
    addr: u64,
    dim_by_id: &HashMap<u32, NcDimension>,
) -> Result<u32, NcError> {
    // Resolve the object at `addr` to get its attributes.
    let obj = h5.object_at(addr)?;
    let (attr_views, ds_name) = match obj {
        oxih5::ObjectKind::Dataset(ref ds) => {
            // We don't have a path here, so we work with the dataset's stored attrs
            // directly (no vlen/object-ref decode needed for _Netcdf4Dimid).
            let views = ds.attrs().to_vec();
            (views, String::new())
        }
        oxih5::ObjectKind::Group(_) => {
            return Err(NcError::Unsupported("dim scale is a group".into()));
        }
    };

    // Look for _Netcdf4Dimid in the dataset's attrs.
    for attr in &attr_views {
        if attr.name == "_Netcdf4Dimid" {
            if let Some(id) = attr.as_i64() {
                if let Ok(u) = u32::try_from(id) {
                    return Ok(u);
                }
            }
        }
    }

    // No _Netcdf4Dimid: try to match by shape against known dimensions.
    let _ = ds_name;
    let _ = dim_by_id;
    Err(NcError::Unsupported(format!(
        "cannot resolve dim id for object at address {addr:#x}"
    )))
}

/// Create phony `NcAxis` entries for a variable with no DIMENSION_LIST.
fn create_phony_axes(
    shape: &[u64],
    phony_counter: &mut u32,
    dim_by_id: &mut HashMap<u32, NcDimension>,
) -> Vec<NcAxis> {
    let mut axes = Vec::with_capacity(shape.len());
    for &dim_len in shape {
        let id = *phony_counter;
        *phony_counter += 1;
        let name = phony_dim_name(id);
        dim_by_id.insert(
            id,
            NcDimension {
                name: name.clone(),
                len: dim_len,
                id,
                is_unlimited: false,
            },
        );
        axes.push(NcAxis {
            dim_id: id,
            name,
            len: dim_len,
        });
    }
    axes
}

// ---------------------------------------------------------------------------
// Unit tests (pure, no external fixture required)
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use oxih5::{Dtype, FileWriter};

    /// Write a minimal HDF5 file containing one f64 dataset, return bytes.
    fn make_simple_h5(name: &str, data: &[f64]) -> Vec<u8> {
        let tmp = std::env::temp_dir().join(format!("oxinc_test_{name}.h5"));
        FileWriter::new()
            .write_dataset_f64(name, data, &[data.len()])
            .unwrap()
            .build(&tmp)
            .unwrap();
        std::fs::read(&tmp).unwrap()
    }

    #[test]
    fn test_open_from_bytes_simple() {
        let bytes = make_simple_h5("temperature", &[1.0, 2.0, 3.0]);
        let nc = NcFile::open_from_bytes(&bytes).unwrap();
        let root = nc.root_group().unwrap();
        // Should find "temperature" dataset as a variable
        let var = root
            .variable("temperature")
            .expect("should find temperature");
        assert_eq!(var.shape, vec![3]);
        assert!(matches!(var.dtype, Dtype::Float { size: 8, .. }));
    }

    #[test]
    fn test_phony_dims_for_undimensioned_variable() {
        // A plain HDF5 dataset with no DIMENSION_LIST gets phony dims.
        let bytes = make_simple_h5("lat", &[10.0, 20.0, 30.0, 40.0]);
        let nc = NcFile::open_from_bytes(&bytes).unwrap();
        let root = nc.root_group().unwrap();
        let var = root.variable("lat").unwrap();
        assert_eq!(var.dims.len(), 1);
        // Phony dim names start with "phony_dim_"
        assert!(
            var.dims[0].name.starts_with("phony_dim_"),
            "expected phony dim name, got: {}",
            var.dims[0].name
        );
        assert_eq!(var.dims[0].len, 4);
    }

    #[test]
    fn test_root_group_name() {
        let bytes = make_simple_h5("x", &[1.0]);
        let nc = NcFile::open_from_bytes(&bytes).unwrap();
        let root = nc.root_group().unwrap();
        assert_eq!(root.name, "/");
        assert_eq!(root.path, "/");
    }

    #[test]
    fn test_no_dimensions_scalar() {
        // Scalar dataset (shape=[]) should produce no axes.
        // FileWriter doesn't expose scalar write yet; use a length-1 array as proxy.
        let bytes = make_simple_h5("scalar", &[42.0]);
        let nc = NcFile::open_from_bytes(&bytes).unwrap();
        let root = nc.root_group().unwrap();
        assert!(root.variable("scalar").is_some());
    }
}
